### ISSUE TITLE
Fields of embed

### ISSUE THREAD

**Issue by TrasonCo** [SkyCraft78/DiSky3#2]
[12:50:39 ERROR]: #!#!
[12:50:39 ERROR]: #!#! [Skript] Severe Error:
[12:50:39 ERROR]: #!#! Could not load help.sk
[12:50:39 ERROR]: #!#!
[12:50:39 ERROR]: #!#! Something went horribly wrong with Skript.
[12:50:39 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[12:50:39 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[12:50:39 ERROR]: #!#! Following plugins are probably related to this error in some way:
[12:50:39 ERROR]: #!#! Skar
[12:50:39 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[12:50:39 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[12:50:39 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[12:50:39 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[12:50:39 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[12:50:39 ERROR]: #!#!
[12:50:39 ERROR]: #!#! Stack trace:
[12:50:39 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for embed
[12:50:39 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:262)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1837)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1804)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1552)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1491)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1564)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1498)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1498)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1564)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1525)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:58)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1030)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:53)
[12:50:39 ERROR]: #!#!     at info.itsthesky.disky3.api.skript.EffectSection$1.<init>(EffectSection.java:126)
[12:50:39 ERROR]: #!#!     at info.itsthesky.disky3.api.skript.EffectSection.loadSection(EffectSection.java:126)
[12:50:39 ERROR]: #!#!     at info.itsthesky.disky3.core.skript.properties.embed.ScopeEmbed.init(ScopeEmbed.java:54)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:251)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:80)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1110)
[12:50:39 ERROR]: #!#!     at info.itsthesky.disky3.core.commands.CommandFactory.add(CommandFactory.java:285)
[12:50:39 ERROR]: #!#!     at info.itsthesky.disky3.core.commands.CommandRegistry.init(CommandRegistry.java:125)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1263)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1234)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:669)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$4(ScriptLoader.java:401)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:420)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:464)
[12:50:39 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:976)
[12:50:39 ERROR]: #!#!     at info.itsthesky.skar.api.FileWatcher.lambda$doOnChange$1(FileWatcher.java:41)
[12:50:39 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[12:50:39 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[12:50:39 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427)
[12:50:39 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436)
[12:50:39 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342)
[12:50:39 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130)
[12:50:39 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[12:50:39 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[12:50:39 ERROR]: #!#!
[12:50:39 ERROR]: #!#! Version Information:
[12:50:39 ERROR]: #!#!   Skript: 2.5.3 (latest)
[12:50:39 ERROR]: #!#!     Flavor: skriptlang-github
[12:50:39 ERROR]: #!#!     Date: 2020-12-11
[12:50:39 ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[12:50:39 ERROR]: #!#!   Minecraft: 1.16.5
[12:50:39 ERROR]: #!#!   Java: 16.0.2 (Java HotSpot(TM) 64-Bit Server VM 16.0.2+7-67)
[12:50:39 ERROR]: #!#!   OS: Linux amd64 4.19.0-17-amd64
[12:50:39 ERROR]: #!#!
[12:50:39 ERROR]: #!#! Server platform: Paper
[12:50:39 ERROR]: #!#!
[12:50:39 ERROR]: #!#! Current node: add field named ":desktop: System Commands:" with value "%nl%%join {_syscom::*} by nl%" to fields of embed (help.sk, line 33)
[12:50:39 ERROR]: #!#! Current item: null
[12:50:39 ERROR]: #!#!
[12:50:39 ERROR]: #!#! Thread: Server thread
[12:50:39 ERROR]: #!#!
[12:50:39 ERROR]: #!#! Language: english
[12:50:39 ERROR]: #!#! Link parse mode: DISABLED
[12:50:39 ERROR]: #!#!
[12:50:39 ERROR]: #!#! End of Error.
[12:50:39 ERROR]: #!#!

Newest Disky V3.0 Beta

**Comment by SkyCraft78** [comment]
Are you sure you have the latest?
I can confirm that the current pattern use embedbuilder and not embed

**Comment by TrasonCo** [comment]
nah its fine i figot to delete the olad alpha jar that was the problem and i closed the issuse
