### ISSUE TITLE
Bot wont log on using skript 2.6

### ISSUE THREAD

**Issue by wallace4BR** [SkyCraft78/DiSky3#49]
```code
[15:30:16 WARN]: Exception in thread "Craft Scheduler Thread - 43"
[15:30:16 WARN]: org.apache.commons.lang.UnhandledException: Plugin Skript v2.6-beta2 generated an exception while executing task 96
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source)
        at java.util.concurrent.ConcurrentHashMap.put(Unknown Source)
        at ch.njol.skript.variables.Variables.setLocalVariables(Variables.java:275)
        at info.itsthesky.disky3.api.skript.AsyncEffect.lambda$walk$1(AsyncEffect.java:43)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 4 more
 ```

**Comment by wallace4BR** [comment]
Fixed on skript2.6beta3
