### ISSUE TITLE
All music effects break due to 'Missing Library'

### ISSUE THREAD

**Issue by FokaStudio** [SkyCraft78/DiSky3#56]
*formerly know as latest Nighly*

So basically every effect related to lavaplayer (`depth`, `pitch`, `volume`, `speed`) break in this version and throw 
https://paste.gg/p/anonymous/09ba01ef28ce4ad9a6a874f32d2163bd

**Comment by FokaStudio** [comment]
```
[?:?]
[15:59:02] [lava-daemon-pool-playback-4-thread-1/ERROR]: Error in playback of KmJWG-P0v_E
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.
at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[?:?]
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:293) ~[?:?]
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:249) ~[?:?]
at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[?:?]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57) ~[?:?]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49) ~[?:?]
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[?:?]
Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
lavaplayer.version: 1.3.78
os.arch: aarch64
os.name: Linux
os.version: 5.11.0-1020-oracle at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
at java.lang.Thread.run(Thread.java:831) [?:?]

java.vendor: Oracle Corporation
java.version: 16.0.2
java.runtime.version: 16.0.2+7-67
java.vm.version: 16.0.2+7-67
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Required library was not found
at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadWithFailureCheck(NativeLibraryLoader.java:88) ~[?:?]
at com.sedmelluq.lava.common.natives.NativeLibraryLoader.load(NativeLibraryLoader.java:69) ~[?:?]
at com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader.loadConnectorLibrary(ConnectorNativeLibLoader.java:21) ~[?:?]
at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoderLibrary.getInstance(OpusDecoderLibrary.java:13) ~[?:?]
at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoder.<init>(OpusDecoder.java:20) ~[?:?]
at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:193) ~[?:?]
at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:177) ~[?:?]
at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:93) ~[?:?]
at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaOpusTrackConsumer.consume(MatroskaOpusTrackConsumer.java:46) ~[?:?]
at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:371) ~[?:?]
at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:335) ~[?:?]
at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:320) ~[?:?]
at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:296) ~[?:?]
at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:39) ~[?:?]
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275) ~[?:?]
... 10 more
Caused by: java.lang.UnsatisfiedLinkError: Required library was not found
at com.sedmelluq.lava.common.natives.NativeLibraryLoader.extractLibraryFromResources(NativeLibraryLoader.java:125) ~[?:?]
at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadInternal(NativeLibraryLoader.java:110) ~[?:?]
at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadWithFailureCheck(NativeLibraryLoader.java:84) ~[?:?]
at com.sedmelluq.lava.common.natives.NativeLibraryLoader.load(NativeLibraryLoader.java:69) ~[?:?]
at com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader.loadConnectorLibrary(ConnectorNativeLibLoader.java:21) ~[?:?]
at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoderLibrary.getInstance(OpusDecoderLibrary.java:13) ~[?:?]
at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoder.<init>(OpusDecoder.java:20) ~[?:?]
at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:193) ~[?:?]
at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:177) ~[?:?]
at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:93) ~[?:?]
at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaOpusTrackConsumer.consume(MatroskaOpusTrackConsumer.java:46) ~[?:?]
at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:371) ~[?:?]
at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:335) ~[?:?]
at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:320) ~[?:?]
at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:296) ~[?:?]
at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:39) ~[?:?]
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275) ~[?:?]
... 10 more
``` can confirm it is still present in the lates nightly

**Comment by FokaStudio** [comment]
# REPRODUCING

1) Search and play a track (I used a Youtube URL here)
2) Change either of those options to smth other than the default value

**Comment by SkyCraft78** [comment]
Hello;
I tried with the following code:
```applescript
search in youtube for "https://www.youtube.com/watch?v=eyLml-zzXzw" and store the results in {_r::*}
connect event-bot to voice channel with id "818182473502294073"
play {_r::1} in event-guild
reply with "Playing"
wait 5 second 
set track speed of event-guild to 1.3
reply with "Speeding"
```
And everything worked fine for me;
could you try it and say here if the exception occurs again?

**Comment by FokaStudio** [comment]
I supposed this was tested on the latest nighly build, right?

**Comment by wallace4BR** [comment]
> I supposed this was tested on the latest nighly build, right?

Get the build at discord since actions are failing to build

**Comment by FokaStudio** [comment]
@SkyCraft78 finally had time to test this, still not working for the version from #bots-test

**Comment by FokaStudio** [comment]
Are there any updates on this?

**Comment by FokaStudio** [comment]
Rather than my last comment that was literally `any updates hey skyyyyyyy`, I have something that might be useful
![image](https://user-images.githubusercontent.com/67797297/143621761-c4005500-970a-4963-9167-28ee2a536154.png)
This was taken in JDA's Discord in the #lavaplayer support.

This is the exact same stacktrace that I have posted the first time

**Comment by wallace4BR** [comment]
@FokaStudio did you fixed it?

**Comment by FokaStudio** [comment]
@wallace4BR not yet. Idk if there is a way for me to fix this sadly...
it might also be just my fairly limited knowldedge that stops me from doing so

**Comment by SkyCraft78** [comment]
Okay so I'm back after further research, and have unfortunately bad news;
This cannot be implemented with DiSky, simply because it's a software core that missing and not a simple library that I could compile.
Try to search the defaults files for natives on the web that your OS could miss, install them and try again, it could fix it but I'm not sure.

Anyway, DiSky cannot do anything since I cannot compile any
