### ISSUE TITLE
Role name not working

### ISSUE THREAD

**Issue by AfonsoHackers** [SkyCraft78/DiSky3#60]
```
[00:01:44] [Server thread/WARN]: #!#! 
[00:01:44] [Server thread/WARN]: #!#! [Skript] Severe Error:
[00:01:44] [Server thread/WARN]: #!#! 
[00:01:44] [Server thread/WARN]: #!#! Something went horribly wrong with Skript.
[00:01:44] [Server thread/WARN]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[00:01:44] [Server thread/WARN]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[00:01:44] [Server thread/WARN]: #!#! Following plugins are probably related to this error in some way:
[00:01:44] [Server thread/WARN]: #!#! DiSky (https://disky.itsthesky.info/) 
[00:01:44] [Server thread/WARN]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[00:01:44] [Server thread/WARN]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[00:01:44] [Server thread/WARN]: #!#! In that case, you will be given instruction on how should you report it.
[00:01:44] [Server thread/WARN]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[00:01:44] [Server thread/WARN]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[00:01:44] [Server thread/WARN]: #!#! 
[00:01:44] [Server thread/WARN]: #!#! Stack trace:
[00:01:44] [Server thread/WARN]: #!#! java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Ljava.lang.String; ([Ljava.lang.Object; and [Ljava.lang.String; are in module java.base of loader 'bootstrap')
[00:01:44] [Server thread/WARN]: #!#!     at ch.njol.skript.effects.EffBroadcast.execute(EffBroadcast.java:65)
[00:01:44] [Server thread/WARN]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
[00:01:44] [Server thread/WARN]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[00:01:44] [Server thread/WARN]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[00:01:44] [Server thread/WARN]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[00:01:44] [Server thread/WARN]: #!#!     at info.itsthesky.disky3.core.commands.CommandObject.lambda$execute$2(CommandObject.java:102)
[00:01:44] [Server thread/WARN]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81)
[00:01:44] [Server thread/WARN]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
[00:01:44] [Server thread/WARN]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1123)
[00:01:44] [Server thread/WARN]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:379)
[00:01:44] [Server thread/WARN]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1071)
[00:01:44] [Server thread/WARN]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:910)
[00:01:44] [Server thread/WARN]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:256)
[00:01:44] [Server thread/WARN]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[00:01:44] [Server thread/WARN]: #!#! 
[00:01:44] [Server thread/WARN]: #!#! Version Information:
[00:01:44] [Server thread/WARN]: #!#!   Skript: 2.5.3
[00:01:44] [Server thread/WARN]: #!#!     Flavor: skriptlang-github
[00:01:44] [Server thread/WARN]: #!#!     Date: 2020-12-11
[00:01:44] [Server thread/WARN]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[00:01:44] [Server thread/WARN]: #!#!   Minecraft: 1.16.5
[00:01:44] [Server thread/WARN]: #!#!   Java: 16.0.2 (OpenJDK 64-Bit Server VM 16.0.2+7-67)
[00:01:44] [Server thread/WARN]: #!#!   OS: Linux aarch64 5.11.0-1019-oracle
[00:01:44] [Server thread/WARN]: #!#! 
[00:01:44] [Server thread/WARN]: #!#! Server platform: Spigot
[00:01:44] [Server thread/WARN]: #!#! 
[00:01:44] [Server thread/WARN]: #!#! Current node: null
[00:01:44] [Server thread/WARN]: #!#! Current item: broadcast name
[00:01:44] [Server thread/WARN]: #!#! Current trigger: discord command testing (simple event) (profile.sk, line -1)
[00:01:44] [Server thread/WARN]: #!#! 
[00:01:44] [Server thread/WARN]: #!#! Thread: Server thread
[00:01:44] [Server thread/WARN]: #!#! 
[00:01:44] [Server thread/WARN]: #!#! Language: english
[00:01:44] [Server thread/WARN]: #!#! Link parse mode: DISABLED
[00:01:44] [Server thread/WARN]: #!#! 
[00:01:44] [Server thread/WARN]: #!#! End of Error.
[00:01:44] [Server thread/WARN]: #!#! 
```

Code:
```
discord command testing:
	prefixes: c.
	trigger:
		loop all discord roles of event-member:
			broadcast loop-value's role name
```

**Comment by wallace4BR** [comment]
> ```
> [00:01:44] [Server thread/WARN]: #!#! 
> [00:01:44] [Server thread/WARN]: #!#! [Skript] Severe Error:
> [00:01:44] [Server thread/WARN]: #!#! 
> [00:01:44] [Server thread/WARN]: #!#! Something went horribly wrong with Skript.
> [00:01:44] [Server thread/WARN]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
> [00:01:44] [Server thread/WARN]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
> [00:01:44] [Server thread/WARN]: #!#! Following plugins are probably related to this error in some way:
> [00:01:44] [Server thread/WARN]: #!#! DiSky (https://disky.itsthesky.info/) 
> [00:01:44] [Server thread/WARN]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
> [00:01:44] [Server thread/WARN]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
> [00:01:44] [Server thread/WARN]: #!#! In that case, you will be given instruction on how should you report it.
> [00:01:44] [Server thread/WARN]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
> [00:01:44] [Server thread/WARN]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
> [00:01:44] [Server thread/WARN]: #!#! 
> [00:01:44] [Server thread/WARN]: #!#! Stack trace:
> [00:01:44] [Server thread/WARN]: #!#! java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Ljava.lang.String; ([Ljava.lang.Object; and [Ljava.lang.String; are in module java.base of loader 'bootstrap')
> [00:01:44] [Server thread/WARN]: #!#!     at ch.njol.skript.effects.EffBroadcast.execute(EffBroadcast.java:65)
> [00:01:44] [Server thread/WARN]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
> [00:01:44] [Server thread/WARN]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
> [00:01:44] [Server thread/WARN]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
> [00:01:44] [Server thread/WARN]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
> [00:01:44] [Server thread/WARN]: #!#!     at info.itsthesky.disky3.core.commands.CommandObject.lambda$execute$2(CommandObject.java:102)
> [00:01:44] [Server thread/WARN]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81)
> [00:01:44] [Server thread/WARN]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
> [00:01:44] [Server thread/WARN]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1123)
> [00:01:44] [Server thread/WARN]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:379)
> [00:01:44] [Server thread/WARN]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1071)
> [00:01:44] [Server thread/WARN]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:910)
> [00:01:44] [Server thread/WARN]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:256)
> [00:01:44] [Server thread/WARN]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
> [00:01:44] [Server thread/WARN]: #!#! 
> [00:01:44] [Server thread/WARN]: #!#! Version Information:
> [00:01:44] [Server thread/WARN]: #!#!   Skript: 2.5.3
> [00:01:44] [Server thread/WARN]: #!#!     Flavor: skriptlang-github
> [00:01:44] [Server thread/WARN]: #!#!     Date: 2020-12-11
> [00:01:44] [Server thread/WARN]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
> [00:01:44] [Server thread/WARN]: #!#!   Minecraft: 1.16.5
> [00:01:44] [Server thread/WARN]: #!#!   Java: 16.0.2 (OpenJDK 64-Bit Server VM 16.0.2+7-67)
> [00:01:44] [Server thread/WARN]: #!#!   OS: Linux aarch64 5.11.0-1019-oracle
> [00:01:44] [Server thread/WARN]: #!#! 
> [00:01:44] [Server thread/WARN]: #!#! Server platform: Spigot
> [00:01:44] [Server thread/WARN]: #!#! 
> [00:01:44] [Server thread/WARN]: #!#! Current node: null
> [00:01:44] [Server thread/WARN]: #!#! Current item: broadcast name
> [00:01:44] [Server thread/WARN]: #!#! Current trigger: discord command testing (simple event) (profile.sk, line -1)
> [00:01:44] [Server thread/WARN]: #!#! 
> [00:01:44] [Server thread/WARN]: #!#! Thread: Server thread
> [00:01:44] [Server thread/WARN]: #!#! 
> [00:01:44] [Server thread/WARN]: #!#! Language: english
> [00:01:44] [Server thread/WARN]: #!#! Link parse mode: DISABLED
> [00:01:44] [Server thread/WARN]: #!#! 
> [00:01:44] [Server thread/WARN]: #!#! End of Error.
> [00:01:44] [Server thread/WARN]: #!#! 
> ```
> 
> Code:
> 
> ```
> discord command testing:
> 	prefixes: c.
> 	trigger:
> 		loop all discord roles of event-member:
> 			broadcast loop-value's role name
> ```

try broadcast "%loop-role%" or "%loop-value's role name%" or "%role name of loop-role%"

**Comment by SkyCraft78** [comment]
I was able to reproduce it;
I'll work on a fix, thanks for the report!

**Comment by SkyCraft78** [comment]
Just looked a bit in DiSky, no classes seems related to that errors;
Except for command one, which well executes the Skript code, it looks likes it come from Skript directly.
For a workaround, that code worked for me:
```applescript
loop all discord roles of event-member:
    broadcast "%loop-value's role name%"
```
It could be the broadcast effect that cast to String instead of using `toString()` method, or something like that.

**Comment by wallace4BR** [comment]
> Just looked a bit in DiSky, no classes seems related to that errors; Except for command one, which well executes the Skript code, it looks likes it come from Skript directly. For a workaround, that code worked for me:
> 
> ```applescript
> loop all discord roles of event-member:
>     broadcast "%loop-value's role name%"
> ```
> 
> It could be the broadcast effect that cast to String instead of using `toString()` method, or something like that.

Not related to disky at all, skript was trying to broadcast an object since the expression wasnt called to string
