### ISSUE TITLE
[ERROR MESSAGE]

### ISSUE THREAD

**Issue by LowScarlet** [SkyCraft78/DiSky3#65]
```hs
[07:06:42 INFO]: [Skript] Reloading all scripts in discord...
[07:06:42 ERROR]: #!#! 
[07:06:42 ERROR]: #!#! [Skript] Severe Error:
[07:06:42 ERROR]: #!#! Could not load discord/_botLoading.sk
[07:06:42 ERROR]: #!#! 
[07:06:42 ERROR]: #!#! You're running a (buggy) nightly version of Skript.
[07:06:42 ERROR]: #!#! If this is not a test server, switch to a more stable release NOW!
[07:06:42 ERROR]: #!#! Your players are unlikely to appreciate crashes and/or data loss due to Skript bugs.
[07:06:42 ERROR]: #!#! 
[07:06:42 ERROR]: #!#! Just testing things? Good. Please report this bug, so that we can fix it before a stable release.
[07:06:42 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues
[07:06:42 ERROR]: #!#! 
[07:06:42 ERROR]: #!#! Stack trace:
[07:06:42 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "ch.njol.skript.config.SectionNode.iterator()" because "node" is null
[07:06:42 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1100)
[07:06:42 ERROR]: #!#!     at DiSky 3.7.0-ARK.jar//info.itsthesky.disky3.core.skript.botbuilder.BotFactory.build(BotFactory.java:95)
[07:06:42 ERROR]: #!#!     at DiSky 3.7.0-ARK.jar//info.itsthesky.disky3.core.skript.botbuilder.BotRegistry.init(BotRegistry.java:53)
[07:06:42 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1110)
[07:06:42 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1073)
[07:06:42 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:739)
[07:06:42 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[07:06:42 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[07:06:42 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[07:06:42 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[07:06:42 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.ScriptLoader.reloadScripts(ScriptLoader.java:1068)
[07:06:42 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[07:06:42 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[07:06:42 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[07:06:42 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876)
[07:06:42 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchServerCommand(CraftServer.java:839)
[07:06:42 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:507)
[07:06:42 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:481)
[07:06:42 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
[07:06:42 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
[07:06:42 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[07:06:42 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[07:06:42 ERROR]: #!#! 
[07:06:42 ERROR]: #!#! Version Information:
[07:06:42 ERROR]: #!#!   Skript: 2.6-nightly-dda6f5a
[07:06:42 ERROR]: #!#!     Flavor: skriptlang-nightly
[07:06:42 ERROR]: #!#!     Date: 14:10:57.894434180
[07:06:42 ERROR]: #!#!   Bukkit: 1.18.1-R0.1-SNAPSHOT
[07:06:42 ERROR]: #!#!   Minecraft: 1.18.1
[07:06:42 ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12-39)
[07:06:42 ERROR]: #!#!   OS: Linux amd64 5.11.0-1020-aws
[07:06:42 ERROR]: #!#! 
[07:06:42 ERROR]: #!#! Server platform: Paper
[07:06:42 ERROR]: #!#! 
[07:06:42 ERROR]: #!#! Current node: null
[07:06:42 ERROR]: #!#! Current item: null
[07:06:42 ERROR]: #!#! 
[07:06:42 ERROR]: #!#! Thread: Server thread
[07:06:42 ERROR]: #!#! 
[07:06:42 ERROR]: #!#! Language: english
[07:06:42 ERROR]: #!#! Link parse mode: DISABLED
[07:06:42 ERROR]: #!#! 
[07:06:42 ERROR]: #!#! End of Error.
[07:06:42 ERROR]: #!#! 
[07:06:42 INFO]: [Skript] Successfully reloaded 1 script in discord.
```
file.sk
```vs
Options:
    base.name: discord

define bot "enderdragon":
    token: #
    intents: default intents
    application:
        application id: #
        application secret: #
```
I just use this code and not work for test created OAuth2 system
I'm sure that I filled in all the data correctly, but sorry I can't share token, id, and secret id

DiSky version 3.7.0
Skript version 2.6-nightly-dda6f5a
This server is running Paper version git-Paper-83 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 6178609)

**Comment by wallace4BR** [comment]
> 

Looks related to [this error](https://github.com/SkriptLang/Skript/issues/4473)

**Comment by wallace4BR** [comment]
Closing as it is an skript error and its not related to disky
[here](https://github.com/SkriptLang/Skript/pull/4476)
